 const jobs = [
    {
      id: 1,
      title: "Senior Software Engineer",
      company: "TechCorp Solutions",
      location: "San Francisco, CA",
      type: "full-time",
      salary: "$120k - $160k",
      salaryMin: 120000,
      salaryMax: 160000,
      category: "technology",
      experience: "senior",
      description: "Join our innovative team building next-generation software solutions. We're looking for experienced engineers who thrive in fast-paced environments.",
      fullDescription: "As a Senior Software Engineer at TechCorp Solutions, you'll be responsible for designing, developing, and implementing software solutions that drive our business forward. You'll work with cutting-edge technologies and collaborate with cross-functional teams to deliver high-quality products.",
      responsibilities: [
        "Design and develop scalable software solutions",
        "Mentor junior developers and conduct code reviews",
        "Collaborate with product managers and designers",
        "Implement best practices and coding standards",
        "Optimize applications for maximum performance"
      ],
      requirements: [
        "5+ years of software development experience",
        "Strong proficiency in JavaScript/TypeScript",
        "Experience with React, Node.js, and AWS",
        "Bachelor's degree in Computer Science or related field",
        "Excellent problem-solving skills"
      ],
      posted: "2 days ago",
      skills: ["JavaScript", "React", "Node.js", "AWS", "TypeScript", "MongoDB", "Docker"],
      remote: false,
      urgent: false,
      companyLogo: "TC",
      matchScore: 95,
      benefits: ["Health Insurance", "401k", "Flexible Hours", "Stock Options", "Learning Budget"],
      applicants: 42,
      companySize: "1000-5000",
      workCulture: "Fast-paced, Innovative, Collaborative",
      featured: true,
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    },
    {
      id: 2,
      title: "Digital Marketing Manager",
      company: "Marketing Genius",
      location: "New York, NY",
      type: "full-time",
      salary: "$80k - $100k",
      salaryMin: 80000,
      salaryMax: 100000,
      category: "marketing",
      experience: "mid",
      description: "Lead digital marketing campaigns for Fortune 500 clients and drive customer acquisition strategies.",
      fullDescription: "As a Digital Marketing Manager, you'll develop and execute comprehensive digital marketing strategies that increase brand awareness and drive revenue growth.",
      responsibilities: [
        "Develop and implement digital marketing strategies",
        "Manage SEO/SEM and social media campaigns",
        "Analyze campaign performance and optimize ROI",
        "Lead a team of marketing specialists",
        "Collaborate with sales and product teams"
      ],
      requirements: [
        "3+ years of digital marketing experience",
        "Proven track record in SEO/SEM",
        "Experience with marketing analytics tools",
        "Strong leadership and communication skills",
        "Bachelor's degree in Marketing or related field"
      ],
      posted: "1 day ago",
      skills: ["SEO", "Google Ads", "Analytics", "Content Strategy", "Social Media", "Email Marketing"],
      remote: true,
      urgent: true,
      companyLogo: "MG",
      matchScore: 87,
      benefits: ["Remote Work", "Performance Bonus", "Learning Budget", "Health Insurance"],
      applicants: 28,
      companySize: "100-500",
      workCulture: "Creative, Dynamic, Client-focused",
      featured: true,
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    },
    {
      id: 3,
      title: "Financial Analyst",
      company: "FinancePro",
      location: "Chicago, IL",
      type: "full-time",
      salary: "$70k - $90k",
      salaryMin: 70000,
      salaryMax: 90000,
      category: "finance",
      experience: "mid",
      description: "Analyze financial data and provide strategic insights to drive business decisions.",
      fullDescription: "Join our finance team to analyze financial data, create reports, and provide insights that support strategic business decisions.",
      responsibilities: [
        "Analyze financial data and create reports",
        "Develop financial models and forecasts",
        "Monitor financial performance metrics",
        "Prepare budget and variance analysis",
        "Support strategic planning processes"
      ],
      requirements: [
        "2+ years of financial analysis experience",
        "Strong Excel and financial modeling skills",
        "Knowledge of accounting principles",
        "Bachelor's degree in Finance or Accounting",
        "Excellent analytical and communication skills"
      ],
      posted: "3 days ago",
      skills: ["Excel", "SQL", "Financial Modeling", "Python", "Tableau", "Accounting"],
      remote: false,
      urgent: false,
      companyLogo: "FP",
      matchScore: 76,
      benefits: ["Health Insurance", "Retirement Plan", "Tuition Reimbursement", "Bonus"],
      applicants: 35,
      companySize: "500-1000",
      workCulture: "Professional, Analytical, Growth-oriented",
      featured: false,
      image: "https://images.unsplash.com/photo-1554224154-260325c05993?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    },
    {
      id: 4,
      title: "Registered Nurse",
      company: "City General Hospital",
      location: "Boston, MA",
      type: "full-time",
      salary: "$65k - $85k",
      salaryMin: 65000,
      salaryMax: 85000,
      category: "healthcare",
      experience: "mid",
      description: "Provide exceptional patient care in our ICU department with state-of-the-art medical technology.",
      fullDescription: "Join our dedicated healthcare team to provide comprehensive patient care using the latest medical technologies and treatment methodologies.",
      responsibilities: [
        "Provide direct patient care and monitoring",
        "Administer medications and treatments",
        "Collaborate with healthcare team members",
        "Maintain accurate patient records",
        "Educate patients and families"
      ],
      requirements: [
        "Valid RN license in Massachusetts",
        "2+ years of nursing experience",
        "BLS and ACLS certification",
        "Strong clinical and communication skills",
        "Bachelor's degree in Nursing preferred"
      ],
      posted: "1 day ago",
      skills: ["Patient Care", "Medical Records", "Emergency Response", "CPR", "Medication Administration"],
      remote: false,
      urgent: true,
      companyLogo: "CG",
      matchScore: 82,
      benefits: ["Health Insurance", "Shift Differential", "Continuing Education", "Retirement Plan"],
      applicants: 19,
      companySize: "1000-5000",
      workCulture: "Compassionate, Team-oriented, High-paced",
      featured: true,
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    },
    {
      id: 5,
      title: "Frontend Developer",
      company: "StartupXYZ",
      location: "Austin, TX",
      type: "contract",
      salary: "$90k - $110k",
      salaryMin: 90000,
      salaryMax: 110000,
      category: "technology",
      experience: "mid",
      description: "Build beautiful, responsive web applications using React and modern frontend technologies.",
      fullDescription: "As a Frontend Developer, you'll create engaging user experiences and build responsive web applications using cutting-edge technologies.",
      responsibilities: [
        "Develop responsive web applications",
        "Collaborate with UX/UI designers",
        "Optimize applications for performance",
        "Write clean, maintainable code",
        "Participate in code reviews"
      ],
      requirements: [
        "3+ years of frontend development experience",
        "Proficiency in React and TypeScript",
        "Experience with modern CSS frameworks",
        "Knowledge of web performance optimization",
        "Strong problem-solving skills"
      ],
      posted: "4 days ago",
      skills: ["React", "TypeScript", "CSS", "Git", "Jest", "Webpack"],
      remote: true,
      urgent: false,
      companyLogo: "SX",
      matchScore: 91,
      benefits: ["Remote Work", "Flexible Schedule", "Project Bonuses", "Learning Stipend"],
      applicants: 56,
      companySize: "50-200",
      workCulture: "Innovative, Agile, Collaborative",
      featured: false,
      image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    },
    {
      id: 6,
      title: "Data Scientist",
      company: "AI Innovations",
      location: "Seattle, WA",
      type: "full-time",
      salary: "$130k - $170k",
      salaryMin: 130000,
      salaryMax: 170000,
      category: "technology",
      experience: "senior",
      description: "Develop machine learning models and analyze complex datasets to drive business insights.",
      fullDescription: "Join our AI research team to develop advanced machine learning models and extract valuable insights from complex datasets.",
      responsibilities: [
        "Develop and implement machine learning models",
        "Analyze large, complex datasets",
        "Collaborate with cross-functional teams",
        "Present findings to stakeholders",
        "Stay current with AI/ML advancements"
      ],
      requirements: [
        "5+ years of data science experience",
        "Strong Python and ML framework skills",
        "Experience with big data technologies",
        "PhD or Master's in Data Science",
        "Excellent statistical analysis skills"
      ],
      posted: "1 day ago",
      skills: ["Python", "Machine Learning", "SQL", "TensorFlow", "PyTorch", "Data Visualization"],
      remote: true,
      urgent: true,
      companyLogo: "AI",
      matchScore: 96,
      benefits: ["Stock Options", "Research Budget", "Conference Attendance", "Flexible Hours"],
      applicants: 67,
      companySize: "200-500",
      workCulture: "Research-focused, Innovative, Data-driven",
      featured: true,
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"
    }
  ];

  export default jobs